#!/bin/sh

##
# Runit run script for the tilemill nodejs app
#
export IP='curl http://icanhazip.com'
chpst -u root env 'HOME=/home/root' /home/root/tilemill/index.js --server=true --listenHost=0.0.0.0 --coreUrl=$IP:20009 --tileUrl=$IP:20008 2>&1
