#!/bin/sh

##
# Runit run script for the tilemill nodejs app
#

chpst -u root env 'HOME=/home/root' /home/root/tilemill/index.js --server=true --listenHost=0.0.0.0 --coreUrl=$COREURL --tileUrl=$TILEURL 2>&1
