#!/bin/sh

##
# Runit run script for the tilemill nodejs app
#

chpst -u root env 'HOME=/home/root' /home/root/tilemill/index.js --server=true --listenHost=0.0.0.0 --coreUrl=localhost:20009 --tileUrl=localhost:20008 2>&1
